account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [
    path('signin/', auth_views.LoginView.as_view(template_name='account/signin.html'), name='signin'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signout', auth_views.LogoutView.as_view(), name='signout'),
]

blog/urls.py
from django.urls import path

from . import views
from . import write_view
from . import comment_view

app_name = 'blog'

urlpatterns = [
    path('', views.main, name='main'),
    path('detail/<str:slug>', views.post_detail, name="post_detail"),
    path('write', write_view.WriteView.as_view(), name='write'),
    path('comment', comment_view.comment_add, name='comment'),
    path('<category_name>', views.category, name='category'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin_1822/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('', views.main, name='main'),
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.urls import reverse
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.text import slugify
from django.contrib.auth.models import User

import re

# Create your models here.
class Category(MPTTModel):
    subject = models.CharField(max_length=128, unique=True)
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )
    
    class MPTTMeta:
        order_insertion_by = ['subject']

    def __str__(self):
        return self.subject


class Post(models.Model):
    subject = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    category = TreeForeignKey(
        Category,
        related_name='posts',
        on_delete=models.CASCADE
    )
    slug = models.SlugField(max_length=256, null=False, unique=True, allow_unicode=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={"slug":self.slug})

    def get_pure_content(self):
        return re.sub(r"[^\uAC00-\uD7A30-9a-zA-Z\s\(\)\-\.\?\{\}]", "", self.content)

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.subject, allow_unicode=True)
        return super().save(*args, **kwargs)

class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

blog/forms.py
from django import forms
from .models import Category, Post
from mptt.fields import TreeNodeChoiceField

class PostWriteForm(forms.ModelForm):
    category = TreeNodeChoiceField(queryset=Category.objects.all(), level_indicator='-')

    class Meta:
        model = Post
        fields = [
            'subject',
            'content',
            'category',
        ]

account/views.py
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

# Create your views here.
class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('account:signin')
    template_name = 'account/signup.html'

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Category, Post

# Create your views here.
def main(request):
    categories = Category.objects.filter(parent__isnull=True)
    context = {
        'categories':categories,
    }
    return render(request, 'blog/main.html', context)

def category(request, category_name):
    category = get_object_or_404(Category, subject=category_name)

    ctgr_tree = [category.subject]
    parent = category.parent
    while parent:
        ctgr_tree.append(parent.subject)
        parent = parent.parent
    ctgr_tree.reverse()

    context = {
        'category':category,
        'categories':category.children.all(),
        'ctgr_tree':ctgr_tree,
        'posts':category.posts.all().order_by('-created_at'),
    }
    
    return render(request, 'blog/category.html', context)

def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)

    ctgr_tree = [post.category]
    parent = post.category.parent
    while parent:
        ctgr_tree.append(parent.subject)
        parent = parent.parent
    ctgr_tree.reverse()

    context = {
        'post':post,
        'ctgr_tree':ctgr_tree,
        'comments':post.comments.all(),
    }

    return render(request, 'blog/post_detail.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load bootstrap5 %}

    {% bootstrap_css %}

    {% bootstrap_javascript %}

    {% bootstrap_messages %}

    {% load static %}
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <title>Cometlog</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/blog/blog_extra/post_list.html
<div class="container">
    {% for post in posts %}
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-2 h-md-200 shadow-sm position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <div class="category-link mb-2">
                <a class="link-secondary" href="{% url 'blog:category' category_name=post.category %}">{{ post.category }}</a>
            </div>
            <h4 class="card-text mb-0">{{ post.subject }}</h4>
            <div class="mb-1 text-muted">{{ post.created_at|date:"SHORT_DATETIME_FORMAT" }}</div>
            <p class="card-text mb-auto">{{ post.get_pure_content }}</p>
            <a href="{{ post.get_absolute_url }}" class="stretched-link link-dark">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
            <svg class="bd-placeholder-img" width="200" height="200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
    </div>
    {% endfor %}
</div>

templates/blog/category.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    {% include 'header.html' %}
    {% if ctgr_tree %}
    <div class='container mb-2'>
        <a class="small link-secondary" href={% url 'blog:main' %}>Blog</a>
        {% for ctgr in ctgr_tree %}
        <span class="small text-secondary">></span>
        <a class="small link-secondary" href={% url 'blog:category' category_name=ctgr %}>{{ ctgr }}</a>
        {% endfor %}
    </div>
    {% endif %}
    {% include 'blog/blog_extra/post_list.html' %}
    {% if user.is_staff %}
    <div class='container mb-1'> 
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:write' %}">Post Write</a>
    </div>
    {% endif %}
{% endblock%}

templates/blog/main.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    {% include 'header.html' %}
{% endblock%}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load blog_filter %}

{% block content %}
    {% include 'header.html' %}
    {% if ctgr_tree %}
    <div class='container mb-2'>
        <a class="small link-secondary" href={% url 'blog:main' %}>Blog</a>
        {% for ctgr in ctgr_tree %}
        <span class="small text-secondary">></span>
        <a class="small link-secondary" href={% url 'blog:category' category_name=ctgr %}>{{ ctgr }}</a>
        {% endfor %}
    </div>
    {% endif %}
    <div class='container mb-2'>
        <div class='post-content mb-2'>
            <div class='mb-1'>
                <div class="post-header">
                    <h3 class="mb-1" style="font-weight: bold;">{{ post.subject }}</h3>
                    <div class="mb-2 text-muted">{{ post.created_at|date:"SHORT_DATETIME_FORMAT" }}{% if post.updated_at != post.created_at %} | {{ post.updated_at|date:"SHORT_DATETIME_FORMAT" }}{% endif %}</div>
                </div>
                <div class="mb-1">{{ post.content|mark }}</div>
            </div>
            <div class='row mb-1'>
                <div class='col'>
                    {% if ctgr_tree %}
                    <a class="small link-secondary" href={% url 'blog:main' %}>Blog</a>
                    {% for ctgr in ctgr_tree %}
                    <span class="small text-secondary">></span>
                    <a class="small link-secondary" href={% url 'blog:category' category_name=ctgr %}>{{ ctgr }}</a>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class='col-auto'>
                    {% if user.is_staff %}
                    <a class="btn btn-sm btn-outline-secondary" href="#">M</a>
                    <a class="btn btn-sm btn-outline-secondary" href="#">D</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="mb-1">
            {% if user.is_anonymous %}
            {% else %}
            <form method="post" action="{% url 'blog:comment' %}">
                {% csrf_token %}
                <input type="hidden" name="slug" value="{{ post.slug }}">
                <div class="form-comment row mb-1">
                    <div class="col pe-1"><textarea name="comment-content" placeholder="Comment"></textarea></div>
                    <div class="col-auto ps-0"><button class="btn btn-outline-secondary" type="submit">Send</button></div>
                </div>
            </form>
            {% endif %}
            {% if comments %}
            {% for comment in comments %}
            {{ comment.writer }} {{ comment.created_at|date:"SHORT_DATETIME_FORMAT"}} {{ comment.content }}
            {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock%}

templates/blog/post_list.html
<div class="container">
    {% for post in posts %}
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-2 shadow-sm position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <div class="category-link mb-2">
                <a class="link-secondary" href="{% url 'blog:category' category_name=post.category %}">{{ post.category }}</a>
            </div>
            <h4 class="mb-0">{{ post.subject }}</h4>
            <div class="mb-1 text-muted">{{ post.created_at|date:"SHORT_DATETIME_FORMAT" }}</div>
            <p class="card-text mb-auto">{{ post.content }}</p>
            <a href="#" class="stretched-link link-dark">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
            <svg class="bd-placeholder-img" width="200" height="200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
    </div>
    {% endfor %}
</div>

templates/blog/write.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    {% include 'header.html' %}
    <div class="container">
        <form method="post" action="{% url 'blog:write' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class='mb-1 w-100'>Subject</div>
            <div class='mb-1 w-100'>{{ form.subject }}</div>
            <div class='mb-1 w-100'>Content</div>
            <div class='mb-1 w-100'>{{ form.content }}</div>
            <div class='mb-1 w-100'>Category</div>
            <div class='mb-1 w-100'>{{ form.category }}</div>
            <button class="btn btn-outline-secondary" type="submit">Submit</button>
        </form>
    </div>
{% endblock%}

templates/form_errors.html
{% if form.errors %}
{% for field in form %}
{% if field.errors %}
{% for error in field.errors %}
<div class="alert alert-dark d-flex justify-content-between">
    <strong>{{ field.label }}</strong>
    {{ error }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-dark d-flex justify-content-between">
    {{ error }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

templates/header.html
<div class="container mb-1">
    <header class="header-blog py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-3 pt-1">
                <a class="link-secondary" href="https://github.com/uham" target="_blank">Github</a>
            </div>
            <div class="col-6 text-center">
                <a class="header-blog-logo text-dark" href="{% url 'blog:main' %}">Cometlog</a>
            </div>
            <div class="col-3 d-flex justify-content-end align-items-center">
                {% if user.is_anonymous %}
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'account:signin' %}">Sign in</a>
                {% else %}
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'account:signout' %}">Sign out</a>
                {% endif %}
            </div>
        </div>
    </header>
    {% if categories %}
    <div class="nav-scroller py-1 header-blog">
        <nav class="nav d-flex justify-content-between">
            {% for category in categories %}
            <a class="py-2 pe-2 link-secondary" href="{% url 'blog:category' category_name=category.subject %}">{{ category.subject }}</a>
            {% endfor %}
        </nav>
    </div>
    {% endif %}
</div>